version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_WEBHOOK_URL=https://mikeusdominus.app.n8n.cloud/webhook-test/proposal-writer
    restart: unless-stopped
